/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upfm.upfm;

import javax.swing.JOptionPane;
import static upfm.upfm.HomeForm.loggedInUser;

/**
 *
 * @author User
 */
public class extrafeatureFrame extends javax.swing.JFrame {
     DatabaseManager db = new DatabaseManager();

    /**
     * Creates new form extrafeatureFrame
     */
    public extrafeatureFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                Bkash bkashInstance= new Bkash(loggedInUser.getUsername(),loggedInUser.getPhoneNumber());
    Nagad nagadInstance= new Nagad(loggedInUser.getUsername(),loggedInUser.getPhoneNumber());
    Rocket rocketInstance= new Rocket(loggedInUser.getUsername(),loggedInUser.getPhoneNumber());
       User BankUser = new User(HomeForm.loggedInUser.getUsername(),HomeForm.loggedInUser.getPassword(),HomeForm.loggedInUser.getEmail(),HomeForm.loggedInUser.getPhoneNumber());
    BankAccount bankInstance = new BankAccount(BankUser.getUsername());
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        amnt = new javax.swing.JTextField();
        addmoney = new javax.swing.JButton();
        paybill = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        acc = new javax.swing.JTextField();
        mb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Amount");

        addmoney.setText("Add Money To Bkash");
        addmoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addmoneyMouseClicked(evt);
            }
        });

        paybill.setText("Pay Bill");
        paybill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paybillMouseClicked(evt);
            }
        });

        jLabel2.setText("AddFrom(Acc)");

        mb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bkash", "Nagad", "Rocket" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amnt)
                            .addComponent(acc, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(addmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(paybill, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(mb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(amnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addmoney)
                    .addComponent(paybill))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addmoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmoneyMouseClicked
        // TODO add your handling code here:
        if (mb.getSelectedIndex()==0){
                  double senderB = bankInstance.getBalance(db, acc.getText());
    
        
        if (Double.parseDouble(amnt.getText())>senderB){
            JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (!bankInstance.getUsername(db, acc.getText()).equals(HomeForm.loggedInUser.getUsername())) {
    JOptionPane.showMessageDialog(null, "You Don't Own this account", "Error", JOptionPane.ERROR_MESSAGE);
}
        else{
            bankInstance.updateBalance(db, acc.getText(), senderB-Double.parseDouble(amnt.getText()));
            bkashInstance.updateBalance(db, loggedInUser.getPhoneNumber(),"Bkash", bkashInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Bkash")+senderB);
        JOptionPane.showMessageDialog(null, "Add Money Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        }else if (mb.getSelectedIndex()==1){
                  double senderB = bankInstance.getBalance(db, acc.getText());
    
        
        if (Double.parseDouble(amnt.getText())>senderB){
            JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (!bankInstance.getUsername(db, acc.getText()).equals(HomeForm.loggedInUser.getUsername())) {
    JOptionPane.showMessageDialog(null, "You Don't Own this account", "Error", JOptionPane.ERROR_MESSAGE);
}
        else{
            bankInstance.updateBalance(db, acc.getText(), senderB-Double.parseDouble(amnt.getText()));
            nagadInstance.updateBalance(db, loggedInUser.getPhoneNumber(),"Nagad", nagadInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Nagad")+senderB);
        JOptionPane.showMessageDialog(null, "Add Money Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        }else        if (mb.getSelectedIndex()==2){
                  double senderB = bankInstance.getBalance(db, acc.getText());
    
        
        if (Double.parseDouble(amnt.getText())>senderB){
            JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (!bankInstance.getUsername(db, acc.getText()).equals(HomeForm.loggedInUser.getUsername())) {
    JOptionPane.showMessageDialog(null, "You Don't Own this account", "Error", JOptionPane.ERROR_MESSAGE);
}
        else{
            bankInstance.updateBalance(db, acc.getText(), senderB-Double.parseDouble(amnt.getText()));
            rocketInstance.updateBalance(db, loggedInUser.getPhoneNumber(),"Rocket", rocketInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Rocket")+senderB);
        JOptionPane.showMessageDialog(null, "Add Money Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_addmoneyMouseClicked

    private void paybillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybillMouseClicked
        // TODO add your handling code here:
         
         
        if (mb.getSelectedIndex()==0){
            double senderB = bkashInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Bkash");
             if (Double.parseDouble(amnt.getText())>senderB){
            JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
                             bkashInstance.updateBalance(db, loggedInUser.getPhoneNumber(),"Bkash", bkashInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Bkash")-senderB);

             JOptionPane.showMessageDialog(null, "Pay Bill Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
             }
            
            
        }else if (mb.getSelectedIndex()==1){
                   double senderB = nagadInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Nagad");
             if (Double.parseDouble(amnt.getText())>senderB){
            JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
                             nagadInstance.updateBalance(db, loggedInUser.getPhoneNumber(),"Nagad", nagadInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Nagad")-senderB);

                          JOptionPane.showMessageDialog(null, "Pay Bill Successful", "Success", JOptionPane.INFORMATION_MESSAGE);

             }
            
        }else if (mb.getSelectedIndex()==2){
                   double senderB = rocketInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Rocket");
             if (Double.parseDouble(amnt.getText())>senderB){
            JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
                             rocketInstance.updateBalance(db, loggedInUser.getPhoneNumber(),"Rocket", bkashInstance.getBalance(db, loggedInUser.getPhoneNumber(), "Rocket")-senderB);
             JOptionPane.showMessageDialog(null, "Pay Bill Successful", "Success", JOptionPane.INFORMATION_MESSAGE);

             }
            
            
        }
        
    }//GEN-LAST:event_paybillMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(extrafeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(extrafeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(extrafeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(extrafeatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new extrafeatureFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc;
    private javax.swing.JButton addmoney;
    private javax.swing.JTextField amnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> mb;
    private javax.swing.JButton paybill;
    // End of variables declaration//GEN-END:variables
}
