/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upfm.upfm;

import static upfm.upfm.HomeForm.loggedInUser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class mbSendForm extends javax.swing.JFrame {

    /**
     * Creates new form mbSendForm
     */
    public mbSendForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        Bkash bkashInstance= new Bkash(loggedInUser.getUsername(),loggedInUser.getPhoneNumber());
    Nagad nagadInstance= new Nagad(loggedInUser.getUsername(),loggedInUser.getPhoneNumber());
    Rocket rocketInstance= new Rocket(loggedInUser.getUsername(),loggedInUser.getPhoneNumber());
      DatabaseManager db = new DatabaseManager();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiverField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sender = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Send Money Through");

        jLabel2.setText("Receiver ");

        jLabel3.setText("Amount");

        sender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bkash", "Nagad", "Rocket" }));
        sender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                senderItemStateChanged(evt);
            }
        });
        sender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderActionPerformed(evt);
            }
        });

        jButton1.setText("Send");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receiverField)
                    .addComponent(amountField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(sender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senderActionPerformed

    private void senderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_senderItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_senderItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        if (sender.getSelectedIndex()==0){
            double senderB=bkashInstance.getBalance(db,loggedInUser.getPhoneNumber() , "Bkash");
            if (senderB>Double.parseDouble(amountField.getText())){
                 JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
            bkashInstance.updateBalance(db, loggedInUser.getPhoneNumber(), "Bkash", senderB-Double.parseDouble(amountField.getText()));
            double receiverB = bkashInstance.getBalance(db,receiverField.getText() , "Bkash");
            bkashInstance.updateBalance(db,receiverField.getText(), "Bkash", receiverB+Double.parseDouble(amountField.getText()));
            JOptionPane.showMessageDialog(null, "Send Money Successful", "Success", JOptionPane.INFORMATION_MESSAGE);

            }
        }
        else if (sender.getSelectedIndex()==2){
            double senderB=bkashInstance.getBalance(db,loggedInUser.getPhoneNumber() , "Rocket");
             if (senderB>Double.parseDouble(amountField.getText())){
                 JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
            bkashInstance.updateBalance(db, loggedInUser.getPhoneNumber(), "Rocket", senderB-Double.parseDouble(amountField.getText()));
            double receiverB = bkashInstance.getBalance(db,receiverField.getText() , "Rocket");
            bkashInstance.updateBalance(db,receiverField.getText(), "Rocket", receiverB+Double.parseDouble(amountField.getText()));
            JOptionPane.showMessageDialog(null, "Send Money Successful", "Success", JOptionPane.INFORMATION_MESSAGE);

             }
        }
        else if (sender.getSelectedIndex()==1){
            double senderB=bkashInstance.getBalance(db,loggedInUser.getPhoneNumber() , "Nagad");
             if (senderB>Double.parseDouble(amountField.getText())){
                 JOptionPane.showMessageDialog(null, "Insufficiend Balance", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
            bkashInstance.updateBalance(db, loggedInUser.getPhoneNumber(), "Nagad", senderB-Double.parseDouble(amountField.getText()));
            double receiverB = bkashInstance.getBalance(db,receiverField.getText() , "Nagad");
            bkashInstance.updateBalance(db,receiverField.getText(), "Nagad", receiverB+Double.parseDouble(amountField.getText()));
            JOptionPane.showMessageDialog(null, "Send Money Successful", "Success", JOptionPane.INFORMATION_MESSAGE);

             }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mbSendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mbSendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mbSendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mbSendForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mbSendForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField receiverField;
    private javax.swing.JComboBox<String> sender;
    // End of variables declaration//GEN-END:variables
}
